stages:
  - test
  - publish

variables:
  npm_config_registry: https://services.ub.uni-leipzig.de/nexus/repository/npm/

npm_run_ci:
  stage: test
  image: node:8
  services:
  - name: mysql:latest
    alias: db
  script:
  - test -d .npm && mv .npm ${HOME}
  - npm install
  - npm run ci
  - mv ${HOME}/.npm .
  variables:
    NODE_ENV: "test"
    MYSQL_HOST: "db"
    MYSQL_PORT: "3306"
    MYSQL_ROOT_PASSWORD: adminpw
  cache:
    key: ${CI_PROJECT_ID}
    paths:
    - .npm
  tags:
  - docker


npm_publish:
  stage: publish
  image: node:8
  only:
  - master
  script:
  - 'echo "//services.ub.uni-leipzig.de/nexus/repository/npm-ubl/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
  - npm publish
  tags:
  - docker
  cache:
    key: "${CI_PROJECT_ID}"
    paths:
    - .npm
