stages:
  - test
  - publish
  - image

variables:
  npm_config_registry: https://services.ub.uni-leipzig.de/nexus/repository/npm/

npm_run_ci:
  stage: test
  image: node:8
  services:
  - name: mysql:latest
    alias: db
  script:
  - test -d .npm && mv .npm ${HOME}
  - npm install
  - npm run ci
  - mv ${HOME}/.npm .
  variables:
    NODE_ENV: "test"
    MYSQL_HOST: "db"
    MYSQL_PORT: "3306"
    MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  cache:
    key: ${CI_PROJECT_ID}
    paths:
    - .npm
  tags:
  - docker


npm_publish:
  stage: publish
  image: node:8
  only:
  - master
  script:
  - 'echo "//services.ub.uni-leipzig.de/nexus/repository/npm-ubl/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
  - npm unpublish --force autoconfig || true
  - npm publish
  tags:
  - docker
  cache:
    key: "${CI_PROJECT_ID}"
    paths:
    - .npm

docker_image:
    stage: image
    only:
    - master
    image: docker:latest
    services:
    - docker:dind
    script:
    - docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD} https://services.ub.uni-leipzig.de:10443/
    - docker build --no-cache --pull -t services.ub.uni-leipzig.de:11443/bdd_dev/${CI_PROJECT_NAME}:latest .
    - docker tag services.ub.uni-leipzig.de:11443/bdd_dev/${CI_PROJECT_NAME}:latest services.ub.uni-leipzig.de:11443/bdd_dev/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
    - docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD} https://services.ub.uni-leipzig.de:11443/
    - docker push services.ub.uni-leipzig.de:11443/bdd_dev/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
    - docker push services.ub.uni-leipzig.de:11443/bdd_dev/${CI_PROJECT_NAME}:latest
    tags:
    - docker