version: '2'
services:
  node:
    image: docker.io/smoebody/dev-nodejs:4
    volumes:
      - ./:/app
      - ../../php/vufind2:/usr/local/vufind2
    ports:
      - "127.0.0.1:9229:9229"
      - "127.0.0.1:5858:5858"
    working_dir: /app
    environment:
      - "NODE_ENV=development"
      - "MYSQL_HOST=db"
      - "MYSQL_PORT=3306"
    command:
      - "npm test"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "127.0.0.1:3306:3306"
